spring.application.name=bff-unificado
server.port=8443

# URLs de los microservicios backend
ms-cuentas.base-url=http://localhost:8081
ms-transacciones.base-url=http://localhost:8094

# Timeouts para llamadas REST
backend.connect-timeout-ms=2000
backend.read-timeout-ms=3000


# Configuración SSL/TLS
server.ssl.enabled=true
server.ssl.key-store=classpath:bff-keystore.p12
server.ssl.key-store-password=password123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=xyzbank